[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rowdybottypiper"
version = "1.2.1"
description = "A bot framework"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "cccarter"}]
license = {text = "MIT"}


dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }
